name: 'Restore GCC from cache'

inputs:
  gcc-version:
    description: 'The GCC version to load (e.g., 16.1.0, 16.2.0)'
    required: false
    default: '16.1.0'

runs:
  using: "composite"
  steps:
    - name: Cache GCC ${{ inputs.gcc-version }}
      id: cache-gcc
      uses: actions/cache@v4
      with:
        path: $HOME/.local/gcc-${{ inputs.gcc-version }}
        key: ${{ runner.os }}-${{ runner.arch }}-gcc-${{ inputs.gcc-version }}

    - name: Check GCC ${{ inputs.gcc-version }} cache load was succeed
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Failed to reload gcc cache!"
        exit 1

    - name: Add GCC ${{ inputs.gcc-version }} to PATH
      shell: bash
      run: echo "$HOME/.local/gcc-${{ inputs.gcc-version }}/bin" >> "$GITHUB_PATH"
